version: '3.8'

services:
  fedora:
    build:
      context: ..\..\
      dockerfile: dockers\fedora\Dockerfile
    image: test_fedora
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    ports:
      - "0.0.0.0:5555:5555"
    container_name: fedora
    environment:
      branche: ""
      mode: ""
      start: ""
    #python3 docker.py <ветка> <режим> <файл который нужно запускать>
    command: ["python3", "docker.py", "${BRANCHE}", "${MODE}", "${START}"]
